spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    learning-management-service:
      writer:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:15432/lms
        username: lms
        password: lms
      reader:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:15432/lms
        username: lms
        password: lms
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
